<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $categoryId = fn (string $slug) => DB::table('medicine_categories')->where('slug', $slug)->value('id');

        $medicines = [
            // المضادات الحيوية
            [
                'name' => 'أموكسيسيلين',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'category_slug' => 'antibiotics',
                'form' => 'capsule',
                'strength' => '500mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'GlaxoSmithKline',
            ],
            [
                'name' => 'أزيثروميسين',
                'generic_name' => 'Azithromycin',
                'brand_name' => 'Zithromax',
                'category_slug' => 'antibiotics',
                'form' => 'tablet',
                'strength' => '250mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Pfizer',
            ],
            [
                'name' => 'سيبروفلوكساسين',
                'generic_name' => 'Ciprofloxacin',
                'brand_name' => 'Cipro',
                'category_slug' => 'antibiotics',
                'form' => 'tablet',
                'strength' => '500mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Bayer',
            ],
            // مسكنات الألم
            [
                'name' => 'باراسيتامول',
                'generic_name' => 'Paracetamol',
                'brand_name' => 'Panadol',
                'category_slug' => 'analgesics',
                'form' => 'tablet',
                'strength' => '500mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'GlaxoSmithKline',
            ],
            [
                'name' => 'إيبوبروفين',
                'generic_name' => 'Ibuprofen',
                'brand_name' => 'Brufen',
                'category_slug' => 'analgesics',
                'form' => 'tablet',
                'strength' => '400mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'Abbott',
            ],
            [
                'name' => 'ديكلوفيناك',
                'generic_name' => 'Diclofenac Sodium',
                'brand_name' => 'Voltaren',
                'category_slug' => 'analgesics',
                'form' => 'tablet',
                'strength' => '50mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Novartis',
            ],
            // الفيتامينات
            [
                'name' => 'فيتامين د',
                'generic_name' => 'Vitamin D3 (Cholecalciferol)',
                'brand_name' => 'Devit-3',
                'category_slug' => 'vitamins-supplements',
                'form' => 'tablet',
                'strength' => '1000 IU',
                'unit' => 'IU',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'Julphar',
            ],
            [
                'name' => 'فيتامين ج',
                'generic_name' => 'Ascorbic Acid',
                'brand_name' => 'Redoxon',
                'category_slug' => 'vitamins-supplements',
                'form' => 'tablet',
                'strength' => '1000mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'Bayer',
            ],
            // أدوية القلب والضغط
            [
                'name' => 'أملوديبين',
                'generic_name' => 'Amlodipine',
                'brand_name' => 'Norvasc',
                'category_slug' => 'cardiovascular',
                'form' => 'tablet',
                'strength' => '5mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Pfizer',
            ],
            [
                'name' => 'ليزينوبريل',
                'generic_name' => 'Lisinopril',
                'brand_name' => 'Zestril',
                'category_slug' => 'cardiovascular',
                'form' => 'tablet',
                'strength' => '10mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'AstraZeneca',
            ],
            // أدوية الجهاز الهضمي
            [
                'name' => 'أوميبرازول',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Losec',
                'category_slug' => 'gastrointestinal',
                'form' => 'capsule',
                'strength' => '20mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'AstraZeneca',
            ],
            [
                'name' => 'ميتوكلوبراميد',
                'generic_name' => 'Metoclopramide',
                'brand_name' => 'Primperan',
                'category_slug' => 'gastrointestinal',
                'form' => 'tablet',
                'strength' => '10mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Sanofi',
            ],
            // أدوية الجهاز التنفسي
            [
                'name' => 'سالبوتامول',
                'generic_name' => 'Salbutamol',
                'brand_name' => 'Ventolin',
                'category_slug' => 'respiratory',
                'form' => 'inhaler',
                'strength' => '100mcg/dose',
                'unit' => 'mcg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'GlaxoSmithKline',
            ],
            // أدوية السكري
            [
                'name' => 'ميتفورمين',
                'generic_name' => 'Metformin HCl',
                'brand_name' => 'Glucophage',
                'category_slug' => 'antidiabetics',
                'form' => 'tablet',
                'strength' => '500mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Merck',
            ],
            [
                'name' => 'إنسولين هيومن',
                'generic_name' => 'Human Insulin',
                'brand_name' => 'Actrapid',
                'category_slug' => 'antidiabetics',
                'form' => 'injection',
                'strength' => '100 IU/ml',
                'unit' => 'IU',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Novo Nordisk',
            ],
            // الأدوية النفسية
            [
                'name' => 'سيرترالين',
                'generic_name' => 'Sertraline HCl',
                'brand_name' => 'Zoloft',
                'category_slug' => 'neuropsychiatric',
                'form' => 'tablet',
                'strength' => '50mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Pfizer',
            ],
            // أدوية الحساسية
            [
                'name' => 'سيتيريزين',
                'generic_name' => 'Cetirizine HCl',
                'brand_name' => 'Zyrtec',
                'category_slug' => 'antiallergics',
                'form' => 'tablet',
                'strength' => '10mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'Johnson & Johnson',
            ],
            [
                'name' => 'لوراتادين',
                'generic_name' => 'Loratadine',
                'brand_name' => 'Claritin',
                'category_slug' => 'antiallergics',
                'form' => 'tablet',
                'strength' => '10mg',
                'unit' => 'mg',
                'requires_prescription' => false,
                'is_controlled' => false,
                'manufacturer' => 'Bayer',
            ],
            // الهرمونات
            [
                'name' => 'ليفوثيروكسين',
                'generic_name' => 'Levothyroxine Sodium',
                'brand_name' => 'Synthroid',
                'category_slug' => 'hormones',
                'form' => 'tablet',
                'strength' => '50mcg',
                'unit' => 'mcg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'AbbVie',
            ],
            [
                'name' => 'ديكساميثازون',
                'generic_name' => 'Dexamethasone',
                'brand_name' => 'Decadron',
                'category_slug' => 'hormones',
                'form' => 'tablet',
                'strength' => '4mg',
                'unit' => 'mg',
                'requires_prescription' => true,
                'is_controlled' => false,
                'manufacturer' => 'Merck',
            ],
        ];

        foreach ($medicines as $data) {
            $catId = $categoryId($data['category_slug']);

            DB::table('medicines')->updateOrInsert(
                ['generic_name' => $data['generic_name']],
                [
                    'name' => $data['name'],
                    'generic_name' => $data['generic_name'],
                    'brand_name' => $data['brand_name'],
                    'category_id' => $catId,
                    'form' => $data['form'],
                    'strength' => $data['strength'],
                    'unit' => $data['unit'],
                    'manufacturer' => $data['manufacturer'],
                    'requires_prescription' => $data['requires_prescription'],
                    'is_controlled' => $data['is_controlled'],
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                    'deleted_at' => null,
                ]
            );
        }
    }
}
